### ISSUE TITLE
Direscraper Redux chapter 2: 2nd event spawns no commons

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#233] opened 2021-01-23 22:09 UTC
If you hold out the first event and kill all commons, the 2nd panic event at the elevator wait will spawn no horde. Seems like a holdout related bug.

**Comment by SirPlease** [comment] 2021-01-25 18:16
Confirmed.
This is caused by [l4d2_horde_equaliser](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_horde_equaliser.sp) as it doesn't support multiple events on a map (as pointed out to me by [Rena](https://steamcommunity.com/profiles/76561198043042606/)!

**Comment by SirPlease** [comment] 2021-01-26 05:38
Resolved in Zonemod 1.9.13

**Closed by SirPlease** 2021-01-26 05:38 UTC
Labels: Fixed - Awaiting Push, High Priority, Verified Issue
