### ISSUE TITLE
Passing a campaign and match mode vote crashes server

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#280] opened 2021-05-24 12:24 UTC
If a change campaign and match mode vote pass at the time the server crashes or kicks everyone out of it.

**Comment by SirPlease** [comment] 2021-05-24 12:42
Should already be fixed with https://github.com/SirPlease/L4D2-Competitive-Rework/pull/276

**Comment by A1mDev** [comment] 2021-05-24 12:49
I don't think it's the same, give a crash dump

**Comment by Derpduck** [comment] 2021-05-24 13:08
Had it happen in a game today on SirPlease NY 5.

**Comment by SirPlease** [comment] 2021-05-24 13:53
There's no crash dump for it, but it sounds easy to reproduce.
Important to note is that all the NA Servers haven't been updated with the extension yet because it'll crash the server if players on it and when I had time to upload it, the servers were in use.

**Comment by A1mDev** [comment] 2021-05-24 13:58
because it's not a crash, I myself wonder what it is, but I don't know what it is. More like network packet issues: Received wrong spawn count 4 when at 3
Commencing connection retry to public(aurora-servers.ru:27017)
failed processing
 Dumping messages for channel CLIENT(37.230.137.121:27017) 0x0980D850
Header bits 96, flags == 33
1 messages
0 -----------------------
net_SignonState: type( 7 ) group ( 13 ) size ( 136 bytes ), startbit 6 end bit 270
   net_SignonState: state 7, count 4
RAW(net_SignonState) start
net_SignonState  >>  ̥�x....P؀.........M... cca5c878 01000000 50d88009 00000000 0b000000 4d010000   
net_SignonState  >>  ..,z��u@....!....�A.��u@ 0a162c7a ece57540 01000000 21000000 0ced41ad eef97540   
net_SignonState  >>  ....!................... 01000000 21000000 00000000 00000000 00000000 00000000   
net_SignonState  >>  ........ .`............. 00000000 00000000 2000600f 07000000 04000000 00000000   
net_SignonState  >>  ....................�.g. 00000000 00000000 00000000 00000000 00000000 c02e6706   
net_SignonState  >>   ...........�.g.         20000000 00000000 10000000 c02e6706                     
RAW(net_SignonState) end
Raw
PKT  >>  62..�,..!!..�..�........ 36320000 dc2c0000 21211801 890800c7 01010000 00000000   
PKT  >>  ........�XM[��].].�.ܛ.. 00000000 00040000 c0584d5b ccd75d18 5d999c99 dc9b1b1d   
PKT  >>  .�                       0080                                                    
Bad server address public("aurora-servers.ru:27017")
BinkOpen( s:\games\steamapps\common\left 4 dead 2\left4dead2\media\l4d2_background05.bik )

**Comment by A1mDev** [comment] 2021-05-24 13:59
I think it is better to block this behavior so that there are no double votes

**Comment by SirPlease** [comment] 2021-05-24 14:21
> I think it is better to block this behavior so that there are no double votes. I could add something like this to builtinvotes, but all plugins using the builtinvotes extension will need to be updated

I was under the impression that builtinvotes's native already checked for outstanding votes, if it doesn't work as it should then I'm guessing it only checks for other votes called by builtinvotes.

**Comment by A1mDev** [comment] 2021-05-25 14:38
Fixed double voting - https://github.com/A1mDev/builtinvotes.

**Closed** 2021-05-25 16:19 UTC
