### ISSUE TITLE
Car incap bug is back (in the rework)

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#149] opened 2020-10-05 05:15 UTC
https://clips.twitch.tv/TawdryBusyYamResidentSleeper

**Comment by SirPlease** [comment] 2020-10-05 09:05
Because there's no server indication, is this on SirPlease or Cedapug (Because I assume it's either of the two)

**Comment by SirPlease** [comment] 2020-10-05 12:57
I might have an idea as to why this occured, I'll run some tests after I get home from work.
All I can say for now is thanks for reporting and I'm sorry for your tank 😢

**Comment by LuckyServ** [comment] 2020-10-09 06:26
Unless your servers were not yet updated with this, it hasn't been fixed. Just happened again.

**Comment by SirPlease** [comment] 2020-10-09 08:06
Do you have any video to use as a point of reference?
As the "happened again" isn't quite specific.

Based on your initial report, I could reproduce the issue 10 out of 10 times because you provided video. I've got nothing to go on now.

**Comment by nippletwister69** [comment] 2020-10-09 13:01
https://clips.twitch.tv/FilthyTameDonkeySoBayed

**Comment by LuckyServ** [comment] 2020-10-09 15:18
@nippletwister69 You're a legend, that was exactly the instance I was referring to.

**Comment by SirPlease** [comment] 2020-10-09 17:04
Cheers for the clip, I'll grab myself a test partner and check it out.

**Comment by SirPlease** [comment] 2020-10-09 19:11
Should be fixed now.

**Closed by SirPlease** 2020-10-09 19:11 UTC
