### ISSUE TITLE
Tank control bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#216] opened 2020-12-29 00:34 UTC
If the player selected at the begining of the round leave the game after, it will print a double message saying this same player will be the tank which is not the case. 

https://ibb.co/pn1WxgT

**Comment by lunatixxx** [comment] 2021-01-09 01:04
On another side i have noticed that if a player who have the control of the second tank in a finale leave while he is still alive, the rescue is activating earlier. Or is it a bug caused by last stand update ? I'm not sure.

**Comment by Derpduck** [comment] 2021-08-25 11:20
This code is causing the double print:
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/25fbd653dc71f61f4f070bb6ab1a28b4ac1ed4ee/addons/sourcemod/scripting/l4d_tank_control_eq.sp#L164

I think it is caused by the player_team event firing twice when someone disconnects.
It uses RequestFrame to call the functions, maybe it doesn't execute them in the right order which is why the wrong tank player is printed?


> On another side i have noticed that if a player who have the control of the second tank in a finale leave while he is still alive, you win all points and the escape sequence is activating earlier and you can finish the game without killing him. Or is it a bug caused by last stand update ? I'm not sure.

This isn't new it has always happened since release, when a tank goes AI during a finale it advances to the next stage.

**Comment by lunatixxx** [comment] 2021-09-26 15:06
> On another side i have noticed that if a player who have the control of the second tank in a finale leave while he is still alive, you win all points and the escape sequence is activating earlier and you can finish the game without killing him. Or is it a bug caused by last stand update ? I'm not sure.

https://github.com/Tsuey/L4D2-Community-Update/issues/48

**Comment by lunatixxx** [comment] 2021-11-27 23:49
L 11/28/2021 - 00:32:54: [SM] Exception reported: Client index 0 is invalid
L 11/28/2021 - 00:32:54: [SM] Blaming: tank_control.smx
L 11/28/2021 - 00:32:54: [SM] Call stack trace:
L 11/28/2021 - 00:32:54: [SM]   [0] IsFakeClient
L 11/28/2021 - 00:32:54: [SM]   [1] Line 290, plugin.sp::L4D_OnTryOfferingTankBot
L 11/28/2021 - 00:32:54: [SM]   [3] Call_Finish
L 11/28/2021 - 00:32:54: [SM]   [4] Line 9479, plugin.sp::DTR_CDirector_TryOfferingTankBot

**Comment by SirPlease** [comment] 2021-11-28 00:17
Haven't seen the error pop up myself on the servers, quite a bunch of games played on them already

**Comment by SirPlease** [comment] 2022-11-20 08:22
> On another side i have noticed that if a player who have the control of the second tank in a finale leave while he is still alive, you win all points and the escape sequence is activating earlier and you can finish the game without killing him. Or is it a bug caused by last stand update ? I'm not sure.

Could possibly be fixed, but not related to this plugin.

> Not related but the bug when a player about to have the control of tank is leaving and the tank become stuck inside the body of another infected or completely disappear still happen even with this plugin.

Resolving this Valve issue is not the goal of this plugin, or any plugin in this repo for that matter.
Could possibly deserve its own issue tracker.

> It's been a few times that i see someone receiving tank as 3rd control. Does that only happen when the tank did not get hit?

When the tank disconnects, it passes to another player even if it's second pass.

**Comment by SirPlease** [comment] 2023-05-18 15:23
> Does that mean that a team could keep the tank forever is they do that continuously? The pre frustration seem to reset. Maybe there is a way to force the control to the AI ?

In theory, yes.
The players would however have to cycle disconnect from the server, I don't really see a reason to attempt and patch that in this plugin to be honest 🤔 

> I noticed that this was disabled in the code, don't know why and if it could fix the bug when player disconnect. Does it really happen on official? Only started to see that with tank control installed i'm just unlucky i guess.

This will not resolve the bug with the scores, as the Tank will still pass to AI.
As for Tank passing even if the Tank is 2nd pass, it also happens in official servers, yes.

**Closed** 2024-06-20 05:51 UTC
Labels: Low Priority, Needs Review/Testing
