### ISSUE TITLE
[BUG] Readyup "Round is live!" message will not disappear on custom campaigns

### ISSUE THREAD

**Issue by Fox8284** [SirPlease/L4D2-Competitive-Rework#733] opened 2024-01-22 07:34 UTC
The hint message that says "Round is live!" will never disappear throughout the entire game, but only on custom campaigns. Official campaigns it disappears like normal.

![left4dead2_8Pai5mQWpn](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/117403955/b1865a64-d740-4588-a032-a5d9102ccf33)

And I also get these errors spamming the console. I am using a dedicated Linux server
![librewolf_IhhqIxfd7S](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/117403955/5313d38f-175c-4211-a4e1-8d6a3c2064ab)

**Comment by cy115** [comment] 2024-01-23 09:20
why ues readyup in coop mode.... it`s not necessary

**Comment by Fox8284** [comment] 2024-01-23 19:59
> why ues readyup in coop mode.... it`s not necessary

I want my server to be played both on campaign and versus modes

**Comment by SirPlease** [comment] 2024-01-23 23:24
From your initial message I was under the impression you were running into issues on versus, if this is not the case then I'll have to close this as not planned as this is not a bug and I don't intend to dig through the plugin anytime soon to add full co-op support.

> I want my server to be played both on campaign and versus modes

I think what @cy115 is trying to say is that you don't need to load readyup to be able to play campaign mode, they're optional plugins for a reason 😄 
Servers that run this repository are able to provide any gamemode they wish, `!match` is used to actually load competitive configs.

**Comment by Fox8284** [comment] 2024-01-24 01:15
> From your initial message I was under the impression you were running into issues on versus, if this is not the case then I'll have to close this as not planned as this is not a bug and I don't intend to dig through the plugin anytime soon to add full co-op support.
> 
> > I want my server to be played both on campaign and versus modes
> 
> I think what @cy115 is trying to say is that you don't need to load readyup to be able to play campaign mode, they're optional plugins for a reason 😄 Servers that run this repository are able to provide any gamemode they wish, `!match` is used to actually load competitive configs.

Oh okay I see. Is there a place I can see which each config does? And can I always load one by default only in versus?

**Comment by cy115** [comment] 2024-02-19 09:35
> > From your initial message I was under the impression you were running into issues on versus, if this is not the case then I'll have to close this as not planned as this is not a bug and I don't intend to dig through the plugin anytime soon to add full co-op support.
> > > I want my server to be played both on campaign and versus modes
> > 
> > 
> > I think what @cy115 is trying to say is that you don't need to load readyup to be able to play campaign mode, they're optional plugins for a reason 😄 Servers that run this repository are able to provide any gamemode they wish, `!match` is used to actually load competitive configs.
> 
> Oh okay I see. Is there a place I can see which each config does? And can I always load one by default only in versus?

If you really want this function that need readyup work on coop, you can get my version of readyup.smxhttps://github.com/cy115/Guo-CompetitiveFramework/blob/master/addons/sourcemod/plugins/optional/readyup.smx
:)

**Closed** 2024-04-21 17:51 UTC
