### ISSUE TITLE
The Last Stand: Item Spawns

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#113] opened 2020-09-26 09:00 UTC
It's been brought to my attention that Molotovs and Adrenalines can be found every now and then on The Last Stand, Map 2.

**Comment by honkthebonk2** [comment] 2020-09-28 06:58
I have not been able to replicate seeing adrenaline/molotov spawns yet, but to fix the asymmetrical pill spawns I have set it up in Stripper to delete every item spawn and place 4 consistent pill spawns.

Also, remove it if you'd like, but I've included a temporary fix to delete the shed door, as I for the life of me could not figure out what was causing it to be unbreakable (adding new doors/changing spawnflags had no effect, among other things).

`; --- Make item spawns consistent (4 pills)
filter:
{
	"classname" "weapon_item_spawn"
}
{
	"classname" "weapon_first_aid_kit_spawn"
}
add:
{
	"classname" "weapon_pain_pills_spawn"
	"spawnflags" "2"
	"origin" "-4342 3597 899.99"
	"angles" "90 255 0"
}
{
	"classname" "weapon_pain_pills_spawn"
	"spawnflags" "2"
	"origin" "-4343 3670 900.128"
	"angles" "90 150 0"
}
{
	"classname" "weapon_pain_pills_spawn"
	"spawnflags" "2"
	"origin" "-4345 3635 900.079"
	"angles" "90 315 0"
}
{
	"classname" "weapon_pain_pills_spawn"
	"spawnflags" "2"
	"origin" "-4342 3610 899.723"
	"angles" "90 105 0"
}
; --- Delete shed door so that SI do not get stuck (temporary fix) 
filter:
{
	"hammerid" "1514333"
}
`

The weapon case at the top of the tower also asymmetrical weapon spawns, but since it's only magnums I have not decided to dedicate too much time to it (reported to NF directly).

**Comment by Target5150** [comment] 2020-09-30 12:54
![20200930203355_1](https://user-images.githubusercontent.com/42076548/94686072-de840280-035c-11eb-8a6f-80e731558803.jpg)

"**l4d_no_cans**" plugin's problem?
I think not only this map have this problem.

**Comment by SirPlease** [comment] 2020-10-10 05:39
> ![20200930203355_1](https://user-images.githubusercontent.com/42076548/94686072-de840280-035c-11eb-8a6f-80e731558803.jpg)
> 
> "**l4d_no_cans**" plugin's problem?
> I think not only this map have this problem.

Plugin works fine, I can't reproduce the issue you're having on either my own install or a precise 1:1 copy of the github.

**Comment by Target5150** [comment] 2020-10-10 07:19
> > "**l4d_no_cans**" plugin's problem?
> > I think not only this map have this problem.
> 
> Plugin works fine, I can't reproduce the issue you're having on either my own install or a precise 1:1 copy of the github.

My issue that I posted I think that was outdated,that happened when your global_fliter.cfg removed. the "no_cans" that just guess.Now I try restart this chapter many times I can't see the cans.

**Comment by SirPlease** [comment] 2020-10-10 12:12
> My issue that I posted I think that was outdated,that happened when your global_fliter.cfg removed. the "no_cans" that just guess.Now I try restart this chapter many times I can't see the cans.

Ah, alright.
Thanks for clarifying 👍

**Comment by A1mDev** [comment] 2020-10-19 07:05
I also had a problem with canisters on this map. I just increased the waiting timer from 1 to 6 sec (in plugin l4d_no_cans.smx). The fact is that the canisters will spawn later. Try on empty server with plugin only l4d_no_cans.smx.
`public Action:RoundStartHook( Handle:event, const String:name[], bool:dontBroadcast )
{
    CreateTimer(6.0, RoundStartNoCans); //here :)
}`

**Comment by lunatixxx** [comment] 2020-11-10 23:35
With the global_filter to remove gas cans, i still found them on the passing map 1 and map 4 of dark carnival. If i install this plugin will it break scavenge finales ?

**Comment by lunatixxx** [comment] 2020-11-17 17:55
Confirmed that with the plugin sometimes gascans still spawns.

**Comment by Derpduck** [comment] 2021-05-17 10:33
This issue should be fixed by the updated global_filters, the items on the finale are spawned by point_template entities which was likely spawning the items after the plugins check for them.
The new filters also make the l4d_no_cans plugin issues redundant.


> Also, remove it if you'd like, but I've included a temporary fix to delete the shed door, as I for the life of me could not figure out what was causing it to be unbreakable (adding new doors/changing spawnflags had no effect, among other things).

This is a global issue on finales, see #223

**Closed** 2021-08-15 21:28 UTC
Labels: Low Priority, Needs Review/Testing
