### ISSUE TITLE
This is my last request, so sorry

### ISSUE THREAD

**Issue by yahorang** [SirPlease/L4D2-Competitive-Rework#133] opened 2020-09-30 11:36 UTC
can you add lerpmonitor.sp,  l4d_boss_percent.sp, spechud.sp, and l4d2_horde_equaliser.sp, l4d2_hybrid_scoremod_zone.sp for left4dhooks?
just i want zonemod in my language

**Comment by SirPlease** [comment] 2020-10-03 14:51
You don't need to apologize, I'm "legally" obliged to provide the sourcefile when providing the compiled versions.
The problem is that a lot of plugins we use the source file has either been lost, is outdated or was never provided by its original author.
I'm trying to get on top of that now. 👍 

I've pushed the sourcefiles for the ones you've requested, **except** for _spechud_ as that requires me updating the include for it so it'll take a bit of time as it's not top priority.

**Comment by yahorang** [comment] 2020-10-03 15:10
thanks !!!!!!

**Comment by devilesk** [comment] 2020-10-03 15:41
lerpmonitor.sp gives a couple errors when trying to compile it.
```
lerpmonitor.sp(323) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier

lerpmonitor.sp(324) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier
```

The rest of the new sources compile.

**Comment by SirPlease** [comment] 2020-10-11 10:33
I'll close this for now, you can keep track of Issue #130 if you wish to know whenever Spechud sourcefiles are ready.

**Closed by SirPlease** 2020-10-11 10:33 UTC
